### ISSUE TITLE
Request for setup.py to install numpy

### ISSUE THREAD

**Issue by yunesj** [brentp/fishers_exact_test#17]
It would be great if fisher setup.py would install its requirements. Workaround is to install numpy first, and then install fisher.

Thanks!

```
$ pip install -r requirements.txt   # which requires and may require numpy
...
Collecting numpy==1.10.4 (from -r requirements.txt (line 9))
  Using cached numpy-1.10.4-cp27-cp27mu-manylinux1_x86_64.whl
Collecting fisher==0.1.4 (from -r requirements.txt (line 10))
  Using cached fisher-0.1.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-M7iMPU/fisher/setup.py", line 2, in <module>
        import numpy as np
    ImportError: No module named numpy
```

**Comment by dbolser** [comment]
@yunesj Can you check the latest version please?

**Comment by dbolser** [comment]
I vote close
