### ISSUE TITLE
OverflowError: value too large to convert to int

### ISSUE THREAD

**Issue by zhangrengang** [brentp/fishers_exact_test#34]
```
Traceback (most recent call last):
  File "Stats.py", line 16, in fisher_test
    try: pval = fisher.pvalue(x11, x12, x21, x22).right_tail
  File "src/cfisher.pyx", line 86, in cfisher.pvalue
OverflowError: value too large to convert to int
```
An example of `x11, x12, x21, x22`: `(1, 78, 1406551982, 2642326796)`

**Comment by dbolser** [comment]
Wow... What does scipy say?

**Comment by dbolser** [comment]
@zhangrengang Any update on this?

**Comment by zhangrengang** [comment]
Not yet.
