### ISSUE TITLE
Cannot import after installation

### ISSUE THREAD

**Issue by johanneskoester** [brentp/fishers_exact_test#6]
After installing the package, I get the following when importing:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "./fisher/__init__.py", line 1, in <module>
    from .cfisher import *
ImportError: No module named 'fisher.cfisher'
```

This is under Python 3.3, with current git master.

**Comment by brentp** [comment]
try from a different directory than the source.

**Comment by johanneskoester** [comment]
Thanks, that fixed it. Sorry for bothering you, I should have noticed that myself :-).

**Comment by endrebak** [comment]
I'm having the same problem from any directory:

```python
Python 3.4.3 |Continuum Analytics, Inc.| (default, Mar  6 2015, 12:03:53)
Type "copyright", "credits" or "license" for more information.

IPython 3.1.0 -- An enhanced Interactive Python.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://binstar.org
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import fisher
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-c2e764f3c9cb> in <module>()
----> 1 import fisher

/local/home/endrebak/anaconda/envs/py34/lib/python3.4/site-packages/fisher-0.1.4-py3.4-linux-x86_64.egg/fisher/__init__.py in <module>()
----> 1 from cfisher import *

ImportError: No module named 'cfisher'
```
It works with `2.7` though.

**Comment by jrderuiter** [comment]
Same problem here!

**Comment by brentp** [comment]
@jrderuiter  can you try pulling from master and re-installing?

**Comment by jrderuiter** [comment]
Pulling from master seems to fix the issue.

**Comment by vigneshravi** [comment]
I reinstalled  but still having the same problem for Python3.4

**Comment by endrebak** [comment]
There is a fishers exact in scipy if you do not get this one working: `scipy.stats.fisher_exact`.
